---
title: "Group 23 CA pollution burden"
author: "Krista Finlay and Rammy Salem"
date: "11/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(here)
library(hexbin)
```

####Read in the cesdemographics data as an an object called ces

```{r}
ces <- read_csv(here("data", "ces3demographics.csv")) %>% 
  clean_names()
```

```{r}
ggplot(data = ces, aes(x = white_percent, y = ces_3_0_score)) + # select x- and y-axis variables
  geom_hex()+ # change to 2d hexbin
  labs( x = "Percentage of Population- White", y = "California EnviroScreen Score", title = "Relationship between CalEnviroScreen Scores and Percentage of \nWhite Population per Census Tract") + # changed axis titles
  scale_fill_gradient(low = "navy", high = "orange") +
  theme_minimal()
```

Based on the graph, it appears that generally, the higher the percentage of White individuals per census tract, the lower the CalEnviroScreen 3.0 score. 
